CREATE TABLE IF NOT EXISTS task
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR NOT NULL,
    description TEXT,
    status      VARCHAR NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_deleted  BOOLEAN                  DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_task_name ON task (name);
CREATE INDEX IF NOT EXISTS idx_task_status ON task (status);

CREATE TABLE IF NOT EXISTS time_record
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id      BIGINT                   NOT NULL,
    task_id          BIGINT                   NOT NULL,
    start_time       TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time         TIMESTAMP WITH TIME ZONE NOT NULL,
    work_description TEXT,
    created_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_deleted       BOOLEAN                  DEFAULT FALSE,

    CONSTRAINT fk_time_record_task_id FOREIGN KEY (task_id) REFERENCES task (id) ON DELETE CASCADE,
    CONSTRAINT chk_time_record_time_range CHECK (end_time > start_time)
);

CREATE INDEX IF NOT EXISTS idx_time_record_employee_id_start_time ON time_record (employee_id, start_time); -- Для оптимизации запросов по сотруднику и времени
CREATE INDEX IF NOT EXISTS idx_time_record_task_id ON time_record (task_id);
