package dev.harakki.cdek_task_time_tracker.domain;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Task {

    // PRIMARY KEY, GENERATED BY DEFAULT AS IDENTITY
    private Long id;

    // NOT NULL
    private String name;

    private String description;

    // NOT NULL
    private TaskStatus status;

    // DEFAULT CURRENT_TIMESTAMP
    private Instant createdAt;

    // DEFAULT CURRENT_TIMESTAMP
    private Instant updatedAt;

    // DEFAULT FALSE
    private Boolean isDeleted;

    // Можно еще добавить инкрементируемое поле version для оптимистической блокировки
    // и поле автора ...

}
