package dev.harakki.cdek_task_time_tracker.domain;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TimeRecord {

    // PRIMARY KEY, GENERATED BY DEFAULT AS IDENTITY
    private Long id;

    // NOT NULL
    private Long employeeId;

    // NOT NULL
    private Long taskId;

    // NOT NULL
    private Instant startTime;

    // NOT NULL
    private Instant endTime;

    private String workDescription;

    // DEFAULT CURRENT_TIMESTAMP
    private Instant createdAt;

    // DEFAULT CURRENT_TIMESTAMP
    private Instant updatedAt;

    // DEFAULT FALSE
    private Boolean isDeleted;

}
